'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class view1

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''inpHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inpHide As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''isFormLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isFormLocked As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''XMLFileLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XMLFileLoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''mouseLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mouseLoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''setScrolltoTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents setScrolltoTop As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''scrollField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrollField As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''isValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isValidate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAttendanceData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAttendanceData As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfUtilityData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUtilityData As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''div_position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_position As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''isInitialLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isInitialLoad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFormInstance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFormInstance As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTabToReviewAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTabToReviewAction As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''F8Pressed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F8Pressed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''F9Pressed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F9Pressed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblJavaScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJavaScript As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJavaScript2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJavaScript2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlUCHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCHeader1 As Global.DOTForm0205.UCHeader

    '''<summary>
    '''pnlMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlMainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMainPage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDistrictEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrictEngineer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAreaEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaEngineer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOffice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteMtgDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteMtgDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteMtgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteMtgTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ContractNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContractNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FedProjectNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FedProjectNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoute As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCountyNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountyNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ProjectNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProjectNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConstType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContractorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grdCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCC As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''addCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addCC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AttendenceSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttendenceSection As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAttendance As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddAttendee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAttendee As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''blnShowAttendList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blnShowAttendList As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPicture As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uplPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplPicture As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrowse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''picAttendees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents picAttendees As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtIC1ProjSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjSuperPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjSuperPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjSuperCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjSuperCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjSuperOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjSuperOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1GenSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1GenSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1GenSuperPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1GenSuperPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1GenSuperCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1GenSuperCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1GenSuperOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1GenSuperOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjMgr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjMgrPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjMgrPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjMgrCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjMgrCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC1ProjMgrOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC1ProjMgrOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ConstEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ConstEng As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ConstEngPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ConstEngPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ConstEngCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ConstEngCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ConstEngEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ConstEngEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFEAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEAName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFEAPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEAPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFEACell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEACell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFEAEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFEAEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAreaEngineer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaEngineer2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAreaEngPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaEngPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAreaEngCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaEngCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAreaEngEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaEngEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjSuperPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjSuperPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjSuperCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjSuperCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjSuperEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjSuperEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjInsp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjInsp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjInspPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjInspPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjInspCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjInspCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2ProjInspEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2ProjInspEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEircName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEircName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEricPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEricPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEricCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEricCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEricEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEricEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2PubAffInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2PubAffInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2PubAffPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2PubAffPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2PubAffInfoCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2PubAffInfoCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2PubAffEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2PubAffEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2EmrgyContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2EmrgyContact As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2EmrgyPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2EmrgyPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIC2EmrgyCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIC2EmrgyCell As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grpEmrgyInfoEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpEmrgyInfoEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCorrespond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespond As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RepPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRep As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRep As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RepVis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepVis As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtIIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEarlyStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEarlyStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteEarlyStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEarlyStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLateStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLateStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteLateStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteLateStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTentStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTentStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteTentStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteTentStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optElecDep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optElecDep As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''optPmtFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optPmtFreq As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtIIAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optNAROW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNAROW As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpROWAcquired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpROWAcquired As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optROWAcquired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optROWAcquired As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtIIIA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIIA1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optUtility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optUtility As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpUtilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpUtilities As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdUtility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdUtility As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddUtility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddUtility As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtIIIAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIIAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grdSubcontractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSubcontractor As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddSubcontractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddSubcontractor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtIIB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optDesignatedEEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDesignatedEEO As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtEEOOfficer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEEOOfficer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIB4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIB5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIIB61A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB61A As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optPosters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optPosters As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group27 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIIB7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIB7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optDBEParticipation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDBEParticipation As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpIDBE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpIDBE As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optDBEGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDBEGoal As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpDBEGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpDBEGoal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDBEGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDBEGoal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDBECommitment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDBECommitment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optDBEChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDBEChanged As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtIIC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIIC2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optLtrDBEMob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optLtrDBEMob As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpI3DBEMob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpI3DBEMob As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optDBETruck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDBETruck As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpLabotDBETruck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpLabotDBETruck As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optDBETruckList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDBETruckList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpLaborDBETruckNoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpLaborDBETruckNoList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optTrainees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optTrainees As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpHwyConstTrainees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpHwyConstTrainees As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIID3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIID3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''group18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''group19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group19 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''group19_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group19_2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIVAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIVAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSafetyAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSafetyAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSpecification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSpecification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIVD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIVD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCntrsRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCntrsRep As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCntrsRepPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCntrsRepPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmergContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergContact As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmergContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergContactPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''upKdotContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upKdotContact As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdContact As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddContract As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTrafficContolAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTrafficContolAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''upMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMaterial As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grpMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpMaterial As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddMaterial As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtVB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSectiontext2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSectiontext2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSectiontext3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSectiontext3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIC8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optStoredMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optStoredMaterials As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpStoredMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpStoredMaterials As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVF5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVF5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProjMatAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjMatAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optSurveying control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optSurveying As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIA1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIA7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIA7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optStormwater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optStormwater As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''group4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''group5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtContWPCMKDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContWPCMKDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMetroEngKDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMetroEngKDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optVIIIB1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optVIIIB1c As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVIIIB1CKDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIB1CKDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optVIIIB1d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optVIIIB1d As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVIIIB1DKDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIB1DKDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStormwaterPreconstConfKDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStormwaterPreconstConfKDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''group5_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group5_2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtContWPCMLPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContWPCMLPA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMetroEngLPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMetroEngLPA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optVIIIB1ea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optVIIIB1ea As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVIIIB1CLPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIB1CLPA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optVIIIB1eb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optVIIIB1eb As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVIIIB1DLPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIB1DLPA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStormwaterPreconstConfLPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStormwaterPreconstConfLPA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optEnvProtection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optEnvProtection As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group11 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkVI6DOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6DOD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVI6Ag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6Ag As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVI6KCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6KCC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVI6Parks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6Parks As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVI6KDHE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6KDHE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVI6KHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVI6KHS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtGrading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrading As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optGrading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optGrading As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpGrading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpGrading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optPlanQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optPlanQty As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAsphPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsphPaving As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optAsphPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optAsphPaving As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group16 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optQC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optQC As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optQCSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optQCSubmitted As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group21 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''sectionQC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sectionQC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optLotID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optLotID As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpAsphPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpAsphPaving As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConcPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConcPaving As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optConcPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optConcPaving As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''optQCQASubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optQCQASubmitted As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''optConcPavQCSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optConcPavQCSub As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpConcPaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpConcPaving As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIE1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStructures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStructures As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optStructures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optStructures As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpStructureDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpStructureDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFalsework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFalsework As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optFalsework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optFalsework As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpFalseworkCat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpFalseworkCat1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIF2Cat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIF2Cat1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grpFalseworkCat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpFalseworkCat2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIF2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optContDemoSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optContDemoSuper As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpControlDemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpControlDemo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkControlDemoCatA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkControlDemoCatA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''sectCat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sectCat1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkControlDemoCatB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkControlDemoCatB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''sectCatB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sectCatB As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCatBSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatBSupervisor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkControlDemoCatC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkControlDemoCatC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''sectCatC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sectCatC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCntrlDemoSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCntrlDemoSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFieldErecSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFieldErecSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optFieldErecSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optFieldErecSuper As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpFieldErect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpFieldErect As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtSectiontext4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSectiontext4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFieldErectSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFieldErectSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDrilledShafts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDrilledShafts As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optDrilledShafts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDrilledShafts As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpDrilledShafts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpDrilledShafts As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIF6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIF6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optHaulRoads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optHaulRoads As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''group8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents group8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtVIIIG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIG2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIG2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIII As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIJ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIJ1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIK1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIK2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optVIIIK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optVIIIK3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtVIIIK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIK3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVIIIK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVIIIK4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProjectConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectConstruction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLogoSigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogoSigns As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optLogoSigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optLogoSigns As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''grpLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grpLogo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIXB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIXB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIXAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIXAdditional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMtgAdjourned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMtgAdjourned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlUCSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCSubmit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCSubmit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCSubmit1 As Global.DOTForm0205.UCSubmit

    '''<summary>
    '''pnlUCAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUCAttachment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UCAttachments1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCAttachments1 As Global.DOTForm0205.UCAttachments
End Class
